### ISSUE TITLE
Something went wrong trying to compile the executable, exiting

### ISSUE THREAD

**Issue by fnk0c** [nccgroup/metasploitavevasion#5]
Got an error while trying to generate an payload

    [franco@Arch ~]$ metasploitavevasion 
    ##################################################################
    
    *** AV0id - Metasploit Shell A.V. Avoider Version 1.5  ***
    
    ##################################################################
    ---------------------------------------------------------------------------------------------------------
    [?] What system do you want the Metasploit listenter to run on? Enter 1 or 2 and press enter
    ---------------------------------------------------------------------------------------------------------
    
     1. Use my current system and IP address
    
     2. Use an alternative system, i.e public external address
    
    ---------------------------------------------------------------------------------------------------------
    
    > 2
    
    [-] Alternative system selected
    
    --------------------------------------------------------------------
    [?] What IP address to you want the listener to run on?
    --------------------------------------------------------------------
    
    > 192.168.0.19
    
    ---------------------------------------------------------------------------------------------------------
    [?] What port number do you want to listen on? If on the internet try port 53 if restricted
    ---------------------------------------------------------------------------------------------------------
    
    > 4444
    
    [-] Generating Metasploit payload, please wait...
    
    [ +++++++++++++++++++++++++++++++++++++++++++++++++++++   ]ruby: No such file or directory -- /usr/share/metasploit/msfpayload (LoadError)
    
    --------------------------------------------------------------------------------------------
    [?] How stealthy do you want the file? Enter 1, 2, 3, 4 or 5 and press enter
    --------------------------------------------------------------------------------------------
    
     1. Normal - about 400K payoad  - fast compile - 13/46 A.V. products detected as malicious
    
     2. Stealth - about 1-2 MB payload - fast compile - 12/46 A.V. products detected as malicious
     
     3. Super Stealth - about 10-20MB payload - fast compile - 11/46 A.V. detected as malicious
    
     4. Insane Stealth - about 50MB payload - slower compile - 10/46 A.V. detected as malicious
    
     5. Desperate Stealth - about 100MB payload - slower compile - Not tested with A.V.
    
    ----------------------------------------------------------------------------------------------
    
    > 3
    
    
    [-] Super Stealth selected, please wait a few seconds
    
    [-] Generating random seed for padding...please wait
    
    [ 01100111001001001110111001101010101010110101001010111 ]
    build.c:5:1: error: expected expression before ‘char’
     char comment[512] = "";
     ^
    
    [!] Something went wrong trying to compile the executable, exiting
    
    Script complete, press <enter> to exit

Running on Arch Linux system.

**Comment by Jsitech** [comment]
Tool was using deprecated commands which were removed from Metasploit Framework.... Tool was Updated with Msfvenom... Try Again... Everything should work OK,......

**Comment by fnk0c** [comment]
Now it gives another error

    [!] Unable to find the required gcc program, install i586-mingw32msvc-gcc and try again

Tried to search for package on Arch Linux repository and AUR, but didn't work. Only found ***arm-wince-cegcc-w32api*** but when I try to install it gives error.

**Comment by Jsitech** [comment]
Try this in Arch... su -c 'pacman -S mingw32-{gcc,binutils,runtime}'

**Comment by fnk0c** [comment]
Not found

**Comment by user98765** [comment]
I am also getting the same error as above:

`build.c:5: error: expected expression before ‘char’`

 Using Kali, and mingw32 is installed.

**Comment by Jsitech** [comment]
Tested on Kali and everything is working fine.......The user that received build.c:5: error: expected expression before ‘char’.. delete any previous files created by the tool in an unsuccessful run......To the arch user, please google how to install mingw32 in arch, and try again.......

**Comment by lllama** [comment]
I was able to get something to build on Arch by installing the w64 toolset and then patching avoid.sh to use i686-w64-mingw32-gcc as the compiler.
```
pacman -S community/mingw-w64-gcc
```
to install and then the following patch to make the script use it:
```
diff --git a/avoid.sh b/avoid.sh
old mode 100644
new mode 100755
index 99a43f7..26cb6e3
--- a/avoid.sh
+++ b/avoid.sh
@@ -80,7 +80,7 @@ sleep 3
 clear
 
 #Check for gcc compiler
-which i586-mingw32msvc-gcc >/dev/null 2>&1
+which i686-w64-mingw32-gcc >/dev/null 2>&1
 if [ $? -eq 0 ]; then
     echo ""
 else
@@ -283,9 +283,9 @@ echo '}' >> build.c
 
 ls icons/icon.res >/dev/null 2>&1
 if [ $? -eq 0 ]; then
-    i586-mingw32msvc-gcc -Wall -mwindows icons/icon.res build.c -o "$OUTPUTNAME"
+    i686-w64-mingw32-gcc -Wall -mwindows icons/icon.res build.c -o "$OUTPUTNAME"
 else
-    i586-mingw32msvc-gcc -Wall -mwindows build.c -o "$OUTPUTNAME"
+    i686-w64-mingw32-gcc -Wall -mwindows build.c -o "$OUTPUTNAME"
 fi
 
 # check if file built correctly
```

*Note* that the script also assuming that ```ifconfig``` will be present for getting the IP address, which might not be the case on Arch. As a work around, you can select the second option and manually supply the IP address.

**Comment by Jsitech** [comment]
Latest Update....

Using ip route for ip detection, Compatible with all distros.
For the compiler added a condition to make it compatible for non Kali distro, Arch Friendly.

This should solve the above issues.....

**Comment by fnk0c** [comment]
Thank you @Jsitech

**Comment by hasanali586q** [comment]
> compiler

how did you solve the problem?

**Comment by hasanali586q** [comment]
> Thank you @Jsitech

how did you solve the problem?
