### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Archietuttle** [nccgroup/metasploitavevasion#7]
![image](https://cloud.githubusercontent.com/assets/14151253/9705586/8347c8a8-54c9-11e5-9e11-869be8244a59.jpg)
Everything worked fine until this error:
May you fix this?

**Comment by lllama** [comment]
I was able to get something to build on Arch by installing the w64 toolset and then patching avoid.sh to use i686-w64-mingw32-gcc as the compiler.
```
pacman -S community/mingw-w64-gcc
```
to install and then the following patch to make the script use it:
```
diff --git a/avoid.sh b/avoid.sh
old mode 100644
new mode 100755
index 99a43f7..26cb6e3
--- a/avoid.sh
+++ b/avoid.sh
@@ -80,7 +80,7 @@ sleep 3
 clear
 
 #Check for gcc compiler
-which i586-mingw32msvc-gcc >/dev/null 2>&1
+which i686-w64-mingw32-gcc >/dev/null 2>&1
 if [ $? -eq 0 ]; then
     echo ""
 else
@@ -283,9 +283,9 @@ echo '}' >> build.c
 
 ls icons/icon.res >/dev/null 2>&1
 if [ $? -eq 0 ]; then
-    i586-mingw32msvc-gcc -Wall -mwindows icons/icon.res build.c -o "$OUTPUTNAME"
+    i686-w64-mingw32-gcc -Wall -mwindows icons/icon.res build.c -o "$OUTPUTNAME"
 else
-    i586-mingw32msvc-gcc -Wall -mwindows build.c -o "$OUTPUTNAME"
+    i686-w64-mingw32-gcc -Wall -mwindows build.c -o "$OUTPUTNAME"
 fi
 
 # check if file built correctly
```

*Note* that the script also assuming that ```ifconfig``` will be present for getting the IP address, which might not be the case on Arch. As a work around, you can select the second option and manually supply the IP address.

**Comment by Jsitech** [comment]
Latest Update....

Using ip route for ip detection, Compatible with all distros.
For the compiler added a condition to make it compatible for non Kali distro, Arch Friendly.

This should solve the above issues.....
