### ISSUE TITLE
Add support for Arch/other distros

### ISSUE THREAD

**Issue by lllama** [nccgroup/metasploitavevasion#8]
The script currently makes assumptions about what tools are installed (mingw-gcc, ifconfig, etc) and so won't work on non-Kali distros.

We should perform some more checks to see whether alternative tools are available and use them if possible.

**Comment by Jsitech** [comment]
Last Update....

Using ip route for ip detection, Compatible with all distros.
For the compiler added a condition to make it compatible for non Kali distro, Arch Friendly.
